### PR TITLE
Added UserGuide.md and documentation for the p new command

### PR DESCRIPTION
**Pull request by CSDUMMI**
First file for the User Guide in UserGuide.md
Please add other commands, I'm not going to work through all the code
and search for the most useful commands to add to this first UserGuide.
I don't want this to be a complete documentation of all commands of p.

UserGuide.md should be the first thing people read to learn about p.
And we shouldn't overwhelm them.

### CODE REVIEW

**Comment by CSDUMMI** [comment]
@boxed  What is your problem with this, that you don't merge it?

**Comment by boxed** [comment]
It needs some spelling and grammar work, but we can fix that later. Go ahead and merge. 

Also, I have two kids and a full time job. Things can take time.

**Comment by CSDUMMI** [comment]
Alright, no problem, but I don't have write access

**Comment by boxed** [comment]
You need to accept the invitation :P

**Pull request merged**
